'use client';
import {useEffect,useId,useRef,useState} from 'react';
import Link from '@/components/native-link';
import {copyCitation} from '@/lib/clipboard.mjs';
import {citationStyles,type CitationPart,type CitationStyle} from '@/lib/citations';
type Preview={uncertainNames?:boolean;parts:CitationPart[];text:string};
function escapeHtml(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function CitationPanel({paperId,slug}:{paperId:number;slug:string}){
 const id=useId(),dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const [open,setOpen]=useState(false),[style,setStyle]=useState<CitationStyle>('apa'),[notice,setNotice]=useState(''),[referenceNumber,setReferenceNumber]=useState(1),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const endpoint='/api/papers/'+paperId+'/citation?style='+style+'&number='+referenceNumber,machine=style==='bibtex'||style==='ris';
 async function fetchPreview(signal?:AbortSignal){const response=await fetch(endpoint,{cache:'no-store',credentials:'same-origin',signal});if(!response.ok){setLocked(response.status===401);throw new Error(response.status===401?'Log in to cite this paper.':'Unable to load this citation. Please try again.');}return await response.json() as Preview;}
 useEffect(()=>{if(!open)return;const controller=new AbortController();const load=async()=>{setBusy(true);setPreview(null);setNotice('');setLocked(false);try{const response=await fetch(endpoint,{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(!response.ok){setLocked(response.status===401);throw new Error(response.status===401?'Log in to cite this paper.':'Unable to load this citation. Please try again.');}setPreview(await response.json() as Preview);}catch(error){if(!controller.signal.aborted)setNotice((error as Error).message);}finally{if(!controller.signal.aborted)setBusy(false);}};void load();return()=>controller.abort();},[open,endpoint]);
 async function act(download=false){setBusy(true);try{const data=await fetchPreview();setPreview(data);if(download){const url=URL.createObjectURL(new Blob([data.text],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='kuta-citation.'+(style==='bibtex'?'bib':'ris');link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Citation text downloaded.');}else{const html=machine?null:data.parts.map(p=>p.italic?'<i>'+escapeHtml(p.text)+'</i>':escapeHtml(p.text)).join('');const copied=await copyCitation(data.text,html,dialog.current);setNotice(copied?'Citation copied.':'Clipboard access is blocked. Select the preview and copy it manually.');}}catch(error){setPreview(null);setNotice((error as Error).message);}finally{setBusy(false);}}
 const login='/login?return_to='+encodeURIComponent('/research-papers/'+encodeURIComponent(slug));
 return <div className="citation-entry"><button ref={trigger} className="button button-outline" type="button" aria-haspopup="dialog" aria-controls={id+'-dialog'} onClick={()=>{setOpen(true);dialog.current?.showModal();}}>Cite ▾</button><dialog id={id+'-dialog'} ref={dialog} className="citation-dialog" aria-labelledby={id+'-heading'} onClose={()=>{setOpen(false);setNotice('');trigger.current?.focus();}} onClick={e=>{if(e.target===dialog.current)dialog.current?.close();}}><div className="dialog-head"><h2 id={id+'-heading'}>Cite this research</h2><button className="dialog-close" type="button" aria-label="Close citation menu" onClick={()=>dialog.current?.close()}>×</button></div><label htmlFor={id+'-style'}>Citation format</label><select id={id+'-style'} value={style} onChange={e=>setStyle(e.target.value as CitationStyle)}>{citationStyles.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{(style==='ieee'||style==='vancouver')&&<label>Reference number<input type="number" min="1" max="9999" value={referenceNumber} onChange={e=>setReferenceNumber(Math.max(1,Math.min(9999,Number(e.target.value)||1)))}/></label>}<div className="citation-output" tabIndex={0} aria-label="Citation preview" aria-busy={busy}>{busy?'Loading citation…':preview?.parts.map((part,index)=>part.italic?<em key={index}>{part.text}</em>:<span key={index}>{part.text}</span>)}</div><div className="card-actions"><button className="button button-primary" type="button" disabled={busy||!preview} onClick={()=>void act()}>Copy citation</button>{machine&&<button className="button button-outline" type="button" disabled={busy||!preview} onClick={()=>void act(true)}>Download citation text</button>}{locked&&<Link className="button button-primary" href={login}>Log in to cite</Link>}</div><p className="copy-notice card-toast" role="status" aria-live="polite">{notice}</p>{preview?.uncertainNames&&<p className="citation-note">Some author names lack separate name fields. Verify surname order.</p>}</dialog></div>;
}
