import assert from 'node:assert/strict';
import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import postcss from 'postcss';
import {normalizeKeywords} from '../lib/keywords.mjs';
import {departmentAccents,departmentAccentFor} from '../lib/departments.ts';
import {toPaperDTO,toPublicPaperDTO,toCitationDTO} from '../lib/archive-dto.ts';
import {citation} from '../lib/citations.ts';
import {migrateKeywords} from './migrate-keywords.mjs';
for(const [input,expected] of [[null,[]],['',[]],['[" Research ","research","  Higher   education ",""]',['Research','Higher education']],['AI, archives, AI',['AI','archives']],[['AI',' ai ',null,12,''],['AI']],['[broken',[]],[{},[]]])assert.deepEqual(normalizeKeywords(input),expected);
console.log('PASS: legacy JSON, comma strings, arrays, null, malformed input and deduplication');
const row=toPaperDTO({id:1,year:2026,slug:'test',title:'Metadata',keywords:'AI, AI, Archives',full_text:'PRIVATE',file_url:'PRIVATE',program_slug:'bsba-hrdm'});
const pub=toPublicPaperDTO(row,[],row.keywords,'guest'),cite=toCitationDTO(row,[],'public');
assert.deepEqual(pub.keywords,['AI','Archives']);assert.ok(!JSON.stringify(pub).includes('PRIVATE'));
assert.match(citation(cite,'bibtex'),/keywords = \{AI, Archives\}/);assert.match(citation(cite,'ris'),/KW  - AI\nKW  - Archives/);
console.log('PASS: public metadata boundary and clean BibTeX/RIS keywords');
const fixture='verification/keyword-fixture-'+randomUUID()+'.sqlite',db=new DatabaseSync(fixture);
db.exec('CREATE TABLE local_migrations(name TEXT PRIMARY KEY); CREATE TABLE research_papers(id INTEGER PRIMARY KEY,keywords TEXT,title TEXT,full_text TEXT)');
db.prepare('INSERT INTO research_papers VALUES(?,?,?,?)').run(1,' A, a, B ','Preserved title','Preserved private text');
db.prepare('INSERT INTO research_papers VALUES(?,?,?,?)').run(2,null,'Second title','Second private text');
const before=db.prepare('SELECT * FROM research_papers').all(),result=migrateKeywords(db,fixture);
assert.equal(result.changed,2);assert.ok(fs.existsSync(result.backup));
const snapshot=new DatabaseSync(result.backup,{readOnly:true});assert.deepEqual(snapshot.prepare('SELECT * FROM research_papers').all(),before);snapshot.close();
const after=db.prepare('SELECT * FROM research_papers').all();assert.equal(after.length,2);
for(let i=0;i<2;i++){assert.equal(after[i].title,before[i].title);assert.equal(after[i].full_text,before[i].full_text);}assert.equal(after[0].keywords,'["A","B"]');assert.equal(after[1].keywords,'[]');assert.equal(migrateKeywords(db,fixture).alreadyApplied,true);db.close();
console.log('PASS: backed-up, metadata-only, repeat-safe migration (isolated fixture retained)');
assert.equal(Object.keys(departmentAccents).length,5);assert.equal(departmentAccentFor('unknown').className,'dept-fallback');assert.equal(departmentAccentFor('toString').className,'dept-fallback');
const css=postcss.parse(fs.readFileSync('app/globals.css','utf8')),tokens={};css.walkRules(r=>{if(r.parent.type==='root'&&(r.selector===':root'||r.selector===':root[data-theme="dark"]')){tokens[r.selector]={};r.walkDecls(d=>tokens[r.selector][d.prop]=d.value);}});
const linear=c=>[1,3,5].map(i=>{const v=parseInt(c.slice(i,i+2),16)/255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});
const lum=c=>linear(c).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
let report='# Department palette and contrast\n\nWCAG relative luminance; text/tint minimum 4.5:1; edge/surface minimum 3:1. Department names remain visible alongside every accent.\n\n| Department slug | Theme | Text | Tint | Edge | Bright accent | Text/tint | Edge/surface |\n|---|---|---|---|---|---|---|---|\n';
for(const [theme,t] of [['Light',tokens[':root']],['Dark',{...tokens[':root'],...tokens[':root[data-theme="dark"]']}]])for(const [slug,d] of Object.entries(departmentAccents)){const text=t[d.textToken],tint=t[d.tintToken],edge=t[d.borderToken],r=ratio(text,tint),e=ratio(edge,t['--surface']);assert.ok(r>=4.5,slug+theme+r);assert.ok(e>=3,slug+theme+e);report+=`| ${slug} | ${theme} | ${text} | ${tint} | ${edge} | ${t[d.accentToken]} | ${r.toFixed(2)}:1 | ${e.toFixed(2)}:1 |\n`;}
const matrices={protanopia:[[.152286,1.052583,-.204868],[.114503,.786281,.099216],[-.003882,-.048116,1.051998]],deuteranopia:[[.367322,.860646,-.227968],[.280085,.672501,.047413],[-.011820,.042940,.968881]],tritanopia:[[1.255528,-.076749,-.178779],[-.078411,.930809,.147602],[.004733,.691367,.303900]]};
const simulatedLum=(hex,matrix)=>matrix.map(row=>Math.min(1,Math.max(0,row.reduce((sum,v,i)=>sum+v*linear(hex)[i],0)))).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);
report+='\nApproximate severity-1 linear-sRGB Machado simulations (screening, not an accessibility certification):\n\n| Simulation | Minimum text/tint ratio across both themes |\n|---|---|\n';
for(const [name,matrix] of Object.entries(matrices)){let min=Infinity;for(const t of [tokens[':root'],{...tokens[':root'],...tokens[':root[data-theme="dark"]']}])for(const d of Object.values(departmentAccents)){const a=simulatedLum(t[d.textToken],matrix),b=simulatedLum(t[d.tintToken],matrix),r=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);min=Math.min(min,r);}assert.ok(min>=4.5,name+min);report+='| '+name+' | '+min.toFixed(2)+':1 |\n';}
report+='\nHue differences can converge under these simulations. Department names and program-card numbers preserve identification without color. [Machado primary-source thesis, Appendix A](https://www.inf.ufrgs.br/~oliveira/students_dissertations/Masters/Gustavo_Machado_Masters_thesis_UFRGS_2010.pdf).\n';
report+='\nUnknown department fallback: muted text, soft tint, line edge; its displayed name is retained. See THEME-CONTRAST.md for neutral fallback measurements.\n\nCommon color-vision deficiencies: color is never the only identifier; program names and program-card numbers remain visible. Physical-device testing is listed separately in HEADER-UPDATE.md.\n\n[W3C text contrast](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html), [W3C non-text contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html).\n';
fs.writeFileSync('verification/DEPARTMENT-PALETTE.md',report);console.log(report);
const html=await(await fetch('http://localhost:3000/')).text();assert.equal((html.match(/<h1[ >]/g)||[]).length,1);assert.match(html,/w=44[^" ]* 1x[^"<>]*w=88[^" ]* 2x/);assert.ok(!html.includes('w=3840'));assert.ok(!html.includes('Keywords: [')&&!html.includes('Keywords: [&quot;'));assert.match(html,/Explore research/);assert.match(html,/Browse programs/);
console.log('PASS: one home h1, fixed 44/88 logo, hero actions and no keyword JSON dump');
