import fs from 'node:fs';import assert from 'node:assert/strict';import postcss from 'postcss';import {gzipSync} from 'node:zlib';
const css=fs.readFileSync('app/globals.css','utf8'),root=postcss.parse(css),tokens={};root.walkRules(r=>{if(r.parent.type==='root'&&(r.selector===':root'||r.selector===':root[data-theme="dark"]')){tokens[r.selector]={};r.walkDecls(d=>tokens[r.selector][d.prop]=d.value);}});
const light=tokens[':root'],dark={...light,...tokens[':root[data-theme="dark"]']};const rgb=c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16));const lum=c=>rgb(c).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
let report='# Final theme contrast\n\nValues calculated using WCAG relative luminance. All text pairs meet 4.5:1; borders/focus/progress meet 3:1. Disabled controls retain full contrast (no opacity reduction).\n\n';
for(const [name,t] of [['Light',light],['Dark',dark]]){report+='## '+name+'\n\n| Role | Foreground | Background | Ratio |\n|---|---|---|---|\n';for(const fg of ['--ink','--muted','--green','--line','--focus'])for(const bg of ['--bg','--surface','--soft']){const r=ratio(t[fg],t[bg]);assert.ok(r>=(['--line','--focus'].includes(fg)?3:4.5),name+fg+bg+r);report+=`| ${fg} on ${bg} | ${t[fg]} | ${t[bg]} | ${r.toFixed(2)}:1 |\n`;}
for(const [fg,bg] of [['--on-accent','--green'],['--on-accent','--green-deep'],['--error','--error-bg']]){const r=ratio(t[fg],t[bg]);assert.ok(r>=4.5);report+=`| ${fg} on ${bg} | ${t[fg]} | ${t[bg]} | ${r.toFixed(2)}:1 |\n`;}
report+='\n';}
report+='Text/input/card/dialog: ink or muted on surface. Chips/disabled/footer: ink or muted on soft. Primary buttons: on-accent on green; hover green-deep. Links/progress: green. Focus ring: focus against each neutral layer. Error: error on error-bg. Logo canvas is white solely to retain the supplied image appearance. Decorative shadows, bokeh and backdrop scrim carry no text. Header and mobile menu are opaque. Dialog glass uses a light 6px blur and a near-solid surface.\n\nSources: [W3C text contrast](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html), [W3C non-text contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html).\n';fs.writeFileSync('verification/THEME-CONTRAST.md',report);
const metrics=JSON.parse(fs.readFileSync('verification/UI-METRICS.json'));metrics.cssAfterBytes=Buffer.byteLength(css);metrics.cssAfterGzip=gzipSync(css).length;metrics.backdropDeclarationsAfter=(css.match(/backdrop-filter:/g)||[]).length;const h=await(await fetch('http://localhost:3000/')).text();let bytes=0;for(const m of h.matchAll(/href="([^"]+\.css)"/g))bytes+=Buffer.byteLength(await(await fetch('http://localhost:3000'+m[1])).text());metrics.compiledCssBeforeSourceScopeBytes=JSON.parse(fs.readFileSync('verification/compiled-css-before.json')).beforeBytes;metrics.compiledCssAfterSourceScopeBytes=bytes;fs.writeFileSync('verification/UI-METRICS.json',JSON.stringify(metrics,null,2));console.log(metrics);console.log(report);
